# docker-compose up -d --build
# docker-compose run --rm app go run db/migrate.go up

version: '3.4'

services:
  app:
    image: golang:1.10
    working_dir: "/go/src/github.com/stobita/golang-ca-sample/"
    volumes:
      - '.:/go/src/github.com/stobita/golang-ca-sample/'
    ports:
      - '8080:8080'
    command: 'go run server.go'
    environment:
      DB_USER: gouser
      DB_PASS: gouser
      DB_HOST: db
      DB_NAME: golang_ca_sample
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: golang_ca_sample
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gouser
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '4311:3306'
volumes:
  db-data:
    driver: local
